# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-13 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=18)),
                ('gender', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'a_person',
            },
        ),
        migrations.CreateModel(
            name='PersonOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=18)),
                ('gender', models.BooleanField(default=0)),
            ],
        ),
    ]
